version: "3"

services:
  nginx:
    container_name: nginx-nook
    restart: unless-stopped
    image: nginx:stable-alpine
    volumes:
      - ./static-html:/usr/share/nginx/html
    ports:
      - "8000:80"

networks:
  default:
    external:
      name: web_network